"""Add batch_size column

Revision ID: 396ffffaac51
Revises: 
Create Date: 2025-01-27 09:14:13.493934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396ffffaac51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_batch', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_job', schema=None) as batch_op:
        batch_op.drop_column('file_path')
        batch_op.drop_column('current_batch')
        batch_op.drop_column('batch_size')

    # ### end Alembic commands ###
