"""Add API credentials to FrappeConnection

Revision ID: bc412a4c2651
Revises: 396ffffaac51
Create Date: 2025-01-27 09:27:31.880298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc412a4c2651'
down_revision = '396ffffaac51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frappe_connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('api_secret', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frappe_connection', schema=None) as batch_op:
        batch_op.drop_column('api_secret')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
